import Footer from "./components/Footer";
import Navbar from "./components/navbar";
import "./globals.css"



export const metadata = {
  title: 'KAHANI GALORE',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Navbar />
      <body>{children}</body>
      <Footer />
    </html>
  );
}